// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC01FYDvQBqGQvLDk-aul-IRaxocnVYTxM',
    appId: '1:965428997529:web:4da237ed0402a1bc88b708',
    messagingSenderId: '965428997529',
    projectId: 'ayam-depresi',
    authDomain: 'ayam-depresi.firebaseapp.com',
    storageBucket: 'ayam-depresi.firebasestorage.app',
    measurementId: 'G-Y5VNRL6SZ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4i0r7dtsjWDReEd1Oyj7_9Ld14G8KV34',
    appId: '1:965428997529:android:3e8fa4949f566d8d88b708',
    messagingSenderId: '965428997529',
    projectId: 'ayam-depresi',
    storageBucket: 'ayam-depresi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4txnh-j8O3FUweb30oDVUWV9X1R6atEg',
    appId: '1:965428997529:ios:76ea9b2263adee9988b708',
    messagingSenderId: '965428997529',
    projectId: 'ayam-depresi',
    storageBucket: 'ayam-depresi.firebasestorage.app',
    iosClientId: '965428997529-pjq1bpbq5los2rhn053qo3v948eu735d.apps.googleusercontent.com',
    iosBundleId: 'com.ayamdepresi.ayamDepresi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC01FYDvQBqGQvLDk-aul-IRaxocnVYTxM',
    appId: '1:965428997529:web:770c5f1a947b53ff88b708',
    messagingSenderId: '965428997529',
    projectId: 'ayam-depresi',
    authDomain: 'ayam-depresi.firebaseapp.com',
    storageBucket: 'ayam-depresi.firebasestorage.app',
    measurementId: 'G-G8X6WCFQ31',
  );

}